version: '2.1'
services:
  customer-app:
    image: customer-ms
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      DB_NAME: mysqldb
  mysqldb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: customers
      MYSQL_PASSWORD: sqlroot1
      MYSQL_ROOT_PASSWORD: sqlroot1

      # volumes:
      #    - ./sql/create_transferapp_db.sql:/docker-entrypoint-initdb.d/create_transferapp_db.sql
