version: '2.1'
services:
  account-app:
    image: account-ms
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
    environment:
      DB_NAME: mysqldb
  mysqldb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: accounts
      MYSQL_PASSWORD: sqlroot1
      MYSQL_ROOT_PASSWORD: sqlroot1

      # volumes:
      #    - ./sql/create_transferapp_db.sql:/docker-entrypoint-initdb.d/create_transferapp_db.sql

  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
